"""fix setor column

Revision ID: 635db45284b1
Revises: 2c91df6e6811
Create Date: 2023-07-04 19:19:25.027823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '635db45284b1'
down_revision = '2c91df6e6811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.alter_column('setor',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.alter_column('setor',
               existing_type=sa.String(length=50),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
